// <auto-generated />
namespace OnlineTestApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CandidateQuestionsTableChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CandidateQuestionsTableChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201805071040359_CandidateQuestionsTableChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
